# Generated by Django 6.0.6 on 2026-10-09 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
        ('mappings', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctormapping',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientdoctormapping',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='patientdoctormapping',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='patientdoctormapping',
            index=models.Index(fields=['patient', '-created_at'], name='patient_doc_patient_12a63c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientdoctormapping',
            index=models.Index(fields=['doctor'], name='patient_doc_doctor__5f6c5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientdoctormapping',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor'), name='unique_patient_doctor_assignment'),
        ),
    ]
